# Copyright 2020-2025 Chris Croome
#
# This file is part of the Webarchitects RabbitMQ role.
#
# The Webarchitects RabbitMQ role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects RabbitMQ role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects RabbitMQ role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Restart RabbitMQ
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
  listen: Restart rabbitmq
  tags:
    - rabbitmq

- name: Check services
  ansible.builtin.service_facts:
  listen: Restart rabbitmq
  tags:
    - rabbitmq

- name: Debug rabbitmq-server.service
  ansible.builtin.debug:
    var: ansible_facts.services | community.general.json_query(rabbitmq_jpq.service).state
  listen: Restart rabbitmq
  tags:
    - rabbitmq

# - name: Ensure RabbitMQ is running
#   ansible.builtin.service_facts:
#   until: >-
#     ((ansible_facts.services | community.general.json_query(rabbitmq_jpq.service)).state is defined) and
#     ((ansible_facts.services | community.general.json_query(rabbitmq_jpq.service)).state == "running")
#   retries: 10
#   delay: 2
#   listen: Restart rabbitmq
#   tags:
#     - rabbitmq
...
